name: Rust Benchmark Master

on:
  push:
    branches: [ "master" ]

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
          --project bleuscore \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch master \
          --testbed ubuntu-latest \
          --adapter rust \
          --err \
          cargo bench --all